ALTER TABLE players ADD COLUMN rating_mu TEXT NOT NULL DEFAULT '0.0';
ALTER TABLE players ADD COLUMN rating_tau TEXT NOT NULL DEFAULT '15.0';
ALTER TABLE players ADD COLUMN rating_sigma TEXT NOT NULL DEFAULT '300.0';
ALTER TABLE players ADD COLUMN rating_points TEXT NOT NULL DEFAULT '0.0';
ALTER TABLE players ADD COLUMN rating_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN rating_last_update_ts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN rating_total_games INTEGER NOT NULL DEFAULT 0;
